version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: ubuntu:16.04 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            apt-get update && apt-get install -y curl
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - restore_cache:
          key: v1-{{ cheksum "requirements.txt" }}
      - run:
          name: Install aws cli
          command: |
            apt-get update && apt-get install -y python3
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
#            curl -O https://bootstrap.pypa.io/get-pip.py
#            python3 get-pip.py --user
#            export PATH=~/.local/bin:$PATH
#            source ~/.bashrc
#            pip install awscli --upgrade --user
      - save_cache:
          key: v1-{{ cheksum "requirements.txt" }}
          paths:
            -"venv"
      - run: |
          docker build -t app .
      - run:
          name: Push Docker image
          command: |
            # login aws
            . venv/bin/activate
            aws configure set region $AWS_REGION
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            $(aws ecr get-login)
          
            # push image to ecr
            docker tag app 922555486444.dkr.ecr.us-east-2.amazonaws.com/cuongtv:nginx_circleci_$CIRCLE_BRANCH_$CIRCLE_SHA1
            docker push 922555486444.dkr.ecr.us-east-2.amazonaws.com/cuongtv:nginx_circleci_$CIRCLE_BRANCH_$CIRCLE_SHA1

      - run:
          name: deploy
          command: |
            # deploy
            . venv/bin/activate 
            sh deploy.sh
