version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: cuongtv/nginx-test # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
#      - run: echo "hello world" # run the `echo` command
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
	### build and push Docker image
      - run: |
	  docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t cuongtv/nginx-test:$CIRCLE_BRANCH .
	  docker push cuongtv/nginx-test:$CIRCLE_BRANCH
