version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: 922555486444.dkr.ecr.us-east-2.amazonaws.com/cuongtv:nginx_circleci # the primary container, where your job's commands are run
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.11.76
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
          docker build -t app .
          docker push cuongtv/nginx-test:$CIRCLE_BRANCH
      - run: |
          name: Push Docker image
          command: |
            #login aws
            aws configure set region $AWS_REGION
            $(aws ecr get-login)
          
            #tag
            docker tag app 922555486444.dkr.ecr.us-east-2.amazonaws.com/cuongtv:nginx_circleci_$CIRCLE_BRANCH
            docker push 922555486444.dkr.ecr.us-east-2.amazonaws.com/cuongtv:nginx_circleci_$CIRCLE_BRANCH
